[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[profile.production]
optimizer = true
optimizer_runs = 1000000
via_ir = true
# "settings": {
#   "optimizer": { "enabled": true, "runs": 200 },
#   "viaIR": true
# }


[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"
base = "${BASE_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
arbitrum = { key = "${ARBISCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
